feat: Add Support for EKS Pod Identity
lablabs/terraform-aws-eks-load-balancer-controller pull request #23
Opened 2024-12-11 16:34 UTC by unitmatrix

This pull request implements a new feature to add support for EKS Pod Identity as requested in issue #19 

### Changes
- Added new input variables:
  - `enable_irsa`: Determines whether to enable support for IAM role for service accounts.
  - `enable_pod_identity`: Determines whether to enable support for EKS pod identity.
- Updated the description for disabling IAM role and IAM policy creation.
- Updated `README.md` to reflect the new variables `enable_irsa` and `enable_pod_identity`.

### Additional Notes
- This feature allows users to enable or disable support for EKS Pod Identity and IAM roles for service accounts.
- The default values for the new variables are set to `true` for `enable_irsa` and `false` for `enable_pod_identity`.

Closes #19 

Please review the changes and provide feedback.

2024-12-13 10:02 UTC, jaygridley commented
Hi @unitmatrix, adding support for EKS Pod Identity is a welcomed enhancement, but I would like to approach it without renaming existing IRSA related variables as it introduces unnecessary breaking changes. I would try to approach this as a separate functionality with own file, variables etc. Policy itself can be shared.

2024-12-14 12:36 UTC, unitmatrix commented
### Reply Message

Hi @jaygridley,

Thank you for your feedback. I have made the following changes to address your concerns:

1. **Separate Functionality**:
   - I have implemented the EKS Pod Identity support as a separate functionality with its own file (`iam_pod_identity.tf`) and variables.
   - The existing IRSA-related variables and functionality remain unchanged to avoid any breaking changes.

2. **Shared Policy**:
   - The policy for Pod Identity is defined separately but can be shared if needed.

I believe these changes align with your suggestions and maintain backward compatibility. Please review the updated implementation.

Thank you for your guidance.

Best regards.

2024-12-16 20:08 UTC, jaygridley requested changes
Thanks for the changes. Looking good, but a few cosmetic touches would be nice ;-)

2024-12-16 20:08 UTC, jaygridley commented on variables.tf
> +  description = "Determines whether to enable support for EKS pod identity"
Lets keep the `description` as 3rd attribute of the variable

2024-12-16 20:08 UTC, jaygridley commented on variables.tf
> +variable "pod_identity_role_create" {
Maybe prefix with `eks_` would be more clear?

2024-12-16 20:08 UTC, jaygridley commented on variables.tf
> +  description = "The pod identity role name prefix for LB controller"
```suggestion
  description = "The EKS pod identity role name prefix for LB controller"
```

2024-12-16 20:08 UTC, jaygridley commented on variables.tf
> +  description = "Pod identity resources tags"
```suggestion
  description = "The EKS pod identity resources tags"
```

2024-12-16 20:08 UTC, jaygridley commented on iam_pod_identity.tf
Rename to `eks_pod_identity.tf` for clarity?

2024-12-16 20:08 UTC, jaygridley commented on iam_pod_identity.tf
> +  pod_identity_role_create = var.enabled && var.service_account_create && var.pod_identity_role_create
```suggestion
  eks_pod_identity_role_create = var.enabled && var.service_account_create && var.eks_pod_identity_role_create
```

2024-12-16 20:08 UTC, jaygridley commented on iam_pod_identity.tf
> +  policy = data.aws_iam_policy_document.this[0].json
We need to patch `data "aws_iam_policy_document" "this"` creation condition to
```
count = local.irsa_role_create && (var.irsa_policy_enabled || var.eks_pod_identity_policy_enabled) ? 1 : 0
```

2024-12-16 20:08 UTC, jaygridley commented on iam_pod_identity.tf
> +  pod_identity_role_create = var.enabled && var.service_account_create && var.pod_identity_role_create
I would add `eks_` prefix to all resources here as well

2024-12-17 09:10 UTC, unitmatrix commented
Thank you for the requested changes, @jaygridley. 

### Summary of Changes:
1. **Renamed Variables and Resources:**
   - Updated variable names and resource names to use the `eks_pod_identity` prefix instead of `pod_identity` for clarity and consistency.
   - Example: `pod_identity_role_create` is now `eks_pod_identity_role_create`.

2. **Updated Documentation:**
   - Modified the README and example files to reflect the new variable names.

3. **Logical Condition Update:**
   - Updated the logical condition for the creation of the IAM policy document to ensure that EKS pod identity can be implemented independently of the IRSA role.

Please review the changes and let me know if any further adjustments are needed.

2024-12-17 11:26 UTC, jaygridley commented
I think we just need to update https://github.com/lablabs/terraform-aws-eks-load-balancer-controller/pull/23#issue-2733447671 comment with latest changes in the variables a we are good to go. In the meantime I will try to test this out in our setup.

2024-12-17 11:46 UTC, jaygridley commented
I am considering one more thing by adding also `https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_pod_identity_association` into the module. I think it can help with the integration of EKS Pod identity further.

2024-12-17 13:44 UTC, unitmatrix commented
Hi @jaygridley ,

Thank you for the suggestion. I have added the `aws_eks_pod_identity_association` resource into the module and updated the README accordingly.

Best regards.

---

2024-12-17 14:06 UTC, jaygridley approved these changes
LGTM

2024-12-17 14:06 UTC, merged